### ISSUE TITLE
[BUG] threading.exceptions does not exist 

### ISSUE THREAD

**Issue by steko** [steko/totalopenstation#155]
**Describe the bug**

Commit 6a77a51dc8dff9921056e37a5f67ce7b59623d14 introduced this import in `models/__init__.py`

```
from threading.exceptions import KeyboardInterrupt
```

https://github.com/totalopenstation/totalopenstation/commit/6a77a51dc8dff9921056e37a5f67ce7b59623d14#r56999855

There is no such module. It has never existed in any Python version as far as I can tell. The import must be removed, because using the `models` will always fail. The import was supposed to help with handling of the KeyboardInterrupt (think CTRL-C) during data download from the terminal, because threading normally ignores the KeyboardInterrupt.

**Comment by psolyca** [comment]
Yes, `KeyboardInterrupt` only works on the main thread.

We can send a event from the main thread to the child.
One example : https://gist.github.com/ruedesign/5218221

**Comment by steko** [comment]
Another example http://gregoryzynda.com/python/developer/threading/2018/12/21/interrupting-python-threads.html

**Comment by psolyca** [comment]
Yes, I have seen this one but not read all.

**Comment by steko** [comment]
Just a quick note that I'm trying to work on this issue and understand how to approach it, but so far my efforts have been quite fruitless. I'll share a draft PR to let others comment on what I have been trying.

The problem is that **serial download is the most fragile part of our codebase**. It is very difficult to make changes without breaking things. So the first thing we need is a test suite for it. And I'm struggling with that, too.

**Comment by steko** [comment]
See https://github.com/totalopenstation/totalopenstation/pull/165

**Comment by steko** [comment]
A quick update on this issue. I still haven't figured out how to fix the problem with KeyboardInterrupt and threads. I'm not sure if we can block the release of 0.6 until this is resolved (especially since the current version is probably broken in the same way).

**Comment by lbartoletti** [comment]
How can I reproduce this problem? I don't have any station at the moment.

**Comment by steko** [comment]
> How can I reproduce this problem? I don't have any station at the moment.

That's the problem we are slowly trying to fix in https://github.com/totalopenstation/totalopenstation/pull/165 since we are all unable to test with a real device. Having a robust test suite for the serial download code should be a substitute for that.

**Comment by steko** [comment]
I think we should just remove the broken import statement and the code that handles `KeyboardInterrupt`.
